# Generated by Django 3.2.7 on 2021-09-04 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vocbulary', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('translation', models.TextField()),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
