# Generated by Django 3.2.7 on 2021-09-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_vocbulary_content_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
