# Generated by Django 3.2.7 on 2021-09-07 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_content_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='delete',
            new_name='is_delete',
        ),
    ]
